// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: user/v1/user.proto

package userv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/nexus-commerce/nexus-contracts-go/user/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UserServiceName is the fully-qualified name of the UserService service.
	UserServiceName = "user.v1.UserService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UserServiceAuthenticateProcedure is the fully-qualified name of the UserService's Authenticate
	// RPC.
	UserServiceAuthenticateProcedure = "/user.v1.UserService/Authenticate"
	// UserServiceRegisterProcedure is the fully-qualified name of the UserService's Register RPC.
	UserServiceRegisterProcedure = "/user.v1.UserService/Register"
	// UserServiceGetProfileProcedure is the fully-qualified name of the UserService's GetProfile RPC.
	UserServiceGetProfileProcedure = "/user.v1.UserService/GetProfile"
	// UserServiceUpdateProfileProcedure is the fully-qualified name of the UserService's UpdateProfile
	// RPC.
	UserServiceUpdateProfileProcedure = "/user.v1.UserService/UpdateProfile"
)

// UserServiceClient is a client for the user.v1.UserService service.
type UserServiceClient interface {
	Authenticate(context.Context, *v1.AuthenticateRequest) (*v1.AuthenticateResponse, error)
	Register(context.Context, *v1.RegisterRequest) (*v1.RegisterResponse, error)
	GetProfile(context.Context, *v1.GetProfileRequest) (*v1.GetProfileResponse, error)
	UpdateProfile(context.Context, *v1.UpdateProfileRequest) (*v1.UpdateProfileResponse, error)
}

// NewUserServiceClient constructs a client for the user.v1.UserService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUserServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UserServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	userServiceMethods := v1.File_user_v1_user_proto.Services().ByName("UserService").Methods()
	return &userServiceClient{
		authenticate: connect.NewClient[v1.AuthenticateRequest, v1.AuthenticateResponse](
			httpClient,
			baseURL+UserServiceAuthenticateProcedure,
			connect.WithSchema(userServiceMethods.ByName("Authenticate")),
			connect.WithClientOptions(opts...),
		),
		register: connect.NewClient[v1.RegisterRequest, v1.RegisterResponse](
			httpClient,
			baseURL+UserServiceRegisterProcedure,
			connect.WithSchema(userServiceMethods.ByName("Register")),
			connect.WithClientOptions(opts...),
		),
		getProfile: connect.NewClient[v1.GetProfileRequest, v1.GetProfileResponse](
			httpClient,
			baseURL+UserServiceGetProfileProcedure,
			connect.WithSchema(userServiceMethods.ByName("GetProfile")),
			connect.WithClientOptions(opts...),
		),
		updateProfile: connect.NewClient[v1.UpdateProfileRequest, v1.UpdateProfileResponse](
			httpClient,
			baseURL+UserServiceUpdateProfileProcedure,
			connect.WithSchema(userServiceMethods.ByName("UpdateProfile")),
			connect.WithClientOptions(opts...),
		),
	}
}

// userServiceClient implements UserServiceClient.
type userServiceClient struct {
	authenticate  *connect.Client[v1.AuthenticateRequest, v1.AuthenticateResponse]
	register      *connect.Client[v1.RegisterRequest, v1.RegisterResponse]
	getProfile    *connect.Client[v1.GetProfileRequest, v1.GetProfileResponse]
	updateProfile *connect.Client[v1.UpdateProfileRequest, v1.UpdateProfileResponse]
}

// Authenticate calls user.v1.UserService.Authenticate.
func (c *userServiceClient) Authenticate(ctx context.Context, req *v1.AuthenticateRequest) (*v1.AuthenticateResponse, error) {
	response, err := c.authenticate.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// Register calls user.v1.UserService.Register.
func (c *userServiceClient) Register(ctx context.Context, req *v1.RegisterRequest) (*v1.RegisterResponse, error) {
	response, err := c.register.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GetProfile calls user.v1.UserService.GetProfile.
func (c *userServiceClient) GetProfile(ctx context.Context, req *v1.GetProfileRequest) (*v1.GetProfileResponse, error) {
	response, err := c.getProfile.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// UpdateProfile calls user.v1.UserService.UpdateProfile.
func (c *userServiceClient) UpdateProfile(ctx context.Context, req *v1.UpdateProfileRequest) (*v1.UpdateProfileResponse, error) {
	response, err := c.updateProfile.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// UserServiceHandler is an implementation of the user.v1.UserService service.
type UserServiceHandler interface {
	Authenticate(context.Context, *v1.AuthenticateRequest) (*v1.AuthenticateResponse, error)
	Register(context.Context, *v1.RegisterRequest) (*v1.RegisterResponse, error)
	GetProfile(context.Context, *v1.GetProfileRequest) (*v1.GetProfileResponse, error)
	UpdateProfile(context.Context, *v1.UpdateProfileRequest) (*v1.UpdateProfileResponse, error)
}

// NewUserServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUserServiceHandler(svc UserServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	userServiceMethods := v1.File_user_v1_user_proto.Services().ByName("UserService").Methods()
	userServiceAuthenticateHandler := connect.NewUnaryHandlerSimple(
		UserServiceAuthenticateProcedure,
		svc.Authenticate,
		connect.WithSchema(userServiceMethods.ByName("Authenticate")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceRegisterHandler := connect.NewUnaryHandlerSimple(
		UserServiceRegisterProcedure,
		svc.Register,
		connect.WithSchema(userServiceMethods.ByName("Register")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceGetProfileHandler := connect.NewUnaryHandlerSimple(
		UserServiceGetProfileProcedure,
		svc.GetProfile,
		connect.WithSchema(userServiceMethods.ByName("GetProfile")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceUpdateProfileHandler := connect.NewUnaryHandlerSimple(
		UserServiceUpdateProfileProcedure,
		svc.UpdateProfile,
		connect.WithSchema(userServiceMethods.ByName("UpdateProfile")),
		connect.WithHandlerOptions(opts...),
	)
	return "/user.v1.UserService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UserServiceAuthenticateProcedure:
			userServiceAuthenticateHandler.ServeHTTP(w, r)
		case UserServiceRegisterProcedure:
			userServiceRegisterHandler.ServeHTTP(w, r)
		case UserServiceGetProfileProcedure:
			userServiceGetProfileHandler.ServeHTTP(w, r)
		case UserServiceUpdateProfileProcedure:
			userServiceUpdateProfileHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUserServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUserServiceHandler struct{}

func (UnimplementedUserServiceHandler) Authenticate(context.Context, *v1.AuthenticateRequest) (*v1.AuthenticateResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.v1.UserService.Authenticate is not implemented"))
}

func (UnimplementedUserServiceHandler) Register(context.Context, *v1.RegisterRequest) (*v1.RegisterResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.v1.UserService.Register is not implemented"))
}

func (UnimplementedUserServiceHandler) GetProfile(context.Context, *v1.GetProfileRequest) (*v1.GetProfileResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.v1.UserService.GetProfile is not implemented"))
}

func (UnimplementedUserServiceHandler) UpdateProfile(context.Context, *v1.UpdateProfileRequest) (*v1.UpdateProfileResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.v1.UserService.UpdateProfile is not implemented"))
}
